services:
  minipos-api:
    container_name: minipos-backend
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: sh -c "npm run build && npm run start:production"

  postgres:
    image: postgres:15
    container_name: minipos-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: minipos-pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
